### ISSUE TITLE
Are there plan to support iOS Data Pipelines for Expo apps?

### ISSUE THREAD

**Issue by miguelespinoza** [customerio/customerio-expo-plugin#133]
From what I could tell in the docs, iOS Data Pipeline is supposed to be enabled by default for Expo apps
https://customer.io/docs/sdk/expo/getting-started/#using-the-sdk-as-a-data-pipelines-source

But I was reviewing the [code](https://github.com/customerio/customerio-reactnative/blob/main/ios/CustomerioReactnative.swift#L44-L54) for how the iOS SDK is initialized and it has no reference for adding a `cdpApiKey` as mentioned in the docs [here for iOS](https://customer.io/docs/sdk/ios/quick-start-guide/#2-set-up-your-app).

Is this expected? or is there a way to pass `cdpApiKey` from an Expo app? The CIO types would indicate this is not possible

**Comment by scotttwittrockcio** [comment]
We just released direct Data Pipelines support for iOS Native Apps this week, which is why you see the reference to the `cdpApiKey` in the iOS docs. Currently our Expo Plugin utilizes our [Journeys Track API](https://customer.io/docs/cdp/sources/connections/cio-journeys-api/#enabling-track-apisdks-as-a-source) to get data into Data Pipelines. The Expo plugin utilizes the `siteId` to send data into Journeys, we then route the data to the "Journeys API" source in Data Pipelines for you. We are currently planning to update the Expo Plugin to support a direct Data Pipelines integration in the future, but I'm not able to share the exact timing on that yet.
