### ISSUE TITLE
Customer IO 4.x SDK Support

### ISSUE THREAD

**Issue by itajenglish** [customerio/customerio-expo-plugin#171]
Hi Customer.io team, We are exploring migrating to Customer.io from Segment but hit a roadblock as the latest Customer.io React Native SDK is not supported by this plugin and we would like to use the latest CDP features. Is there an ETA on when this support will be added? Also, is the config plugin generally behind in support for the latest CIO React Native SDK releases?

**Comment by scotttwittrockcio** [comment]
Hi @itajenglish, we are currently finalizing updating our Expo plugin to support our CDP (Data Pipelines) feature set. Work has been progressing smoothly and we hope to have it released by the end of the year. 

Since many features rely on the CIO React Native SDK updates to the Expo plugin sometimes come out a little later. When possible we try to keep them as in sync as we can.
