### ISSUE TITLE
Compatibility with Expo 48

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-expo-plugin#57]
Doc only mentions expo 45 and 46 but expo 47 has been released in Nov 2022 and Expo in Feb 2023. What about supporting them ? It's not helpful to make this plugin available if not maintained.

For instance, I don't think point 3 in the install/config section is needed any more as expo natively requires iOS 13 from v47 (as per [here](https://blog.expo.dev/expo-sdk-47-a0f6f5c038af))

**Comment by jbtheard** [comment]
I'm still trying to figure out how to make it work. I don't expect any specific issues related to 48 but worth updating the doc on your side if it has indeed been tested. Please five me a few days to eventually report back here.

**Comment by levibostian** [comment]
I talked to our Expo developers on the team and they mentioned that they have tested the Expo plugin with Expo version 48. I have submitted a docs update to say that we support version 48. 

Because of this, I will close this issue.

Anyone can feel free to comment on the issue if they have questions or comments.
