### ISSUE TITLE
Clarify Push Notification config

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-expo-plugin#65]
The whole purpose of using an expo plugin is to NOT have to make any edit on any iOS/android files.

I think [this whole paragraph](https://customer.io/docs/sdk/expo/push/#add-push-notification-capabilities-in-xcode) shouldn't exist in your doc, but perhaps it needs to be replaced by something specific ?

**Comment by levibostian** [comment]
We appreciate this feedback, @jbtheard. 

Today, our Expo plugin does not modify the Xcode project to automatically add the push notification capability. That is why [our docs requires](https://customer.io/docs/sdk/expo/push/#add-push-notification-capabilities-in-xcode) that you manually add the capability to your Xcode project. 

I do not have anything to share in regards to a timeline on this feature request, but know that I did create an internal feature request for this with our mobile team. Our team will prioritize the feature from there. 

Since this feature request has been captured internally, I will close this issue here. However, the conversation can continue here so please add comments if you have more to share.
